apiVersion: v1
kind: Secret
metadata:
  name: my-registry-key
data:
  .dockerconfigjson: ###base64-encoded-contents-of-.docker/config.json-file
      ewoJImF1dGhzIjogewoJCSIxNTI3NTQ1ODU5MDQuZGtyLmVjci51cy1lYXN0LTEuYW1hem9uYXdz
LmNvbSI6IHsKCQkJImF1dGgiOiAiUVZkVE9tVjVTbmRaV0d4ellqSkdhMGxxYjJsT00wMHlVekZz
YjAxRVFuZE5hbEpZWTJ0c2VXUkhZM1pOTTI4MVZtMW9WbUZxV2twamJFcDJXVmRhUjJKRVFsaFZX
RVpyVDBob2VWbHFWbmhpUldSelZERkdNVlZXV25OYWJGWjVXbE01Y1dGNlRtRk5iWGcwWTJ4S1Ns
a3laM2hsYlRWUVZXeGtSbVJHU2pOTU1WWXpZV3h3ZVZkck5XbGFSRmw0WldwV2QxZEVVbTlPYTNo
WFQxWmtXV1JVWkhoUlZ6VklUVEl4Y21KcVZYbFNiRlkwWld4VmNtRnRSblpYYTBaaFpESmpNV0pw
T0hsVU1VSjJaRVZXVjFOR2JIZFZha0p4WTIxa2EwMXViekZVUjJocFVYcE5ORTVWVGpGVmEyZ3hT
ekpSZDJOV1dtNVNNbVJTVW10b2JFOUZUa1JsYTFwUVdqQk9SbFpWV2s5alZWcFdZVEpXY2xRd2RG
aFVTSEJJV1dzMVJXTnRiRTFpYm14b1ZXNW9hMDB5VGt0U1NIQlhZVmRzY2xkSGNFdFNSbXhZVFVa
V05HSnFSbkJNTWpWUlRrVjNkMlJwT1d4VFJURkhZakp6ZVZvemFFVlJWMHB6WTIxa1VHUkhkRUpO
TTFvMlUwaFNSMHd5VFhsamJWWXdaV3MwY2xaWWFEWkxNMHBTVWxkb2RFMTZWbkZWYkhCR1drUlNO
R1F3VWpaT01EbEpWVWh2TlZKck9ETlRVemt5WW5wVk1tUkVSbmRhYW14dldsUm9ibG93T1VkVk1r
NXVUWGs1Y1ZSSE1VdFBSMFp2VVRJeFJHTXpWVEJrUlZaVlQxZGtlRTlEZEZSTE1rNTNWbFJvTW1K
WE1EQkxNMEp6V1d4d2NWWnRkM2xXUldoWFpFWmFlbEZzYXpWa1ZHUlJUREJXY0dGcmN6QmpWVFZ0
V2xjMWQwOVVXa3RWUnpnd1pVUmtWbFZ1WXpWalYzUlhVMVpzTUZOdWFFMVRWVkoxWTBkMFQxcHJW
bGhYU0U1d1RVZE9NbHBYVWtKT1IxcDNWRmR3ZVdKWVpFWmtWMGwyVFVaTk0xRXhUbWhXZWs1eFdr
VkZlRTVYV25CU2EzUlZWRlZrVDFsdVJuVlNiWGgzWTI1b2RXRnNiR3BXVlRsM1ZtcEdhVTFJUlRK
YVYyeEZWMjV3TTJGWFVrdFVWVFZ5V1ZaS2RXSlhXbXRqVTNRMVpXMUdibU5HVVhKTlZWSTFZbXhr
U1ZKSFl6RmpWelZQVmtaSk5WSkhPVU5qV0dSdFkxaGFVV0ZZUmxOa1JteENVbFYwVjJJd1VubE5N
amd6WVZVNVdtRlVVbk5VUnpGSlZtc3hiMkpXVGtKVVNHOTZZMnhKTTA1VlkzaFpNMFo1VGxWb2Iy
VlZXbUZUTTNBelRURmtOV0pXWkVKVGJGcGhUVEJXZEdOcVVqUlJNbXhxVm14Q1UxZHJXVFZhTUUw
eVdUTldhRkV4VlRKTmEyTXdVakJTVEdSSE1ETlJia3BSVkRKR01FNUZWazFYYWxaM1VqSlJNRk51
VGxoVE1uQjBWVVpLVVU5VVZYZGpNV1JDVGxVNU5tUkhNWEJaVTNOM1l6SjBTbHBXUWxGa2VsWTFV
akprZGxkRWEzWlpNMnMwVGpOYVVWWXlVa2xqVjBsM1UwZDBRbFZZVmxwVldIQjJZa1JPYzFKdVNY
SlZWbXhaVERCc1ZtRklhSEJVVlhOMllUQlJNVkZZVGxCalJuQXlZbGR3Y0ZZd09IcFZhbEY1VXpJ
ME1GUnJVbGRPYTFZMVUxUkpNbU5YU2xGalJFSjRVMVJHV2xWWVNrOVRSbFkyVG5wQ1ZFMTVPVTlV
VlZaM1ZtdGtRbUpYTUhwT2VtUkVVekJLU1V4Nlp6VlRhMUpHVjFaS2NsUkRjekJXYTJoRFkxYzFh
V1JyU2sxaWJHOTNWVVprZUdScmNFSmhSRlUxU3pKa1dGUlZVbEZPZWtwWFZrVk9WazB4VGxkUk0w
RjVVbnBrYTJGclJrTlRXSEJSVTBWV2EyVllXbTFaTUVaWVV6RmtUV1J0T1dsTGVrVnlVMjB4VTA1
cVVsSlNiWFJ0VjBjeFJGWnFXbmxTU0ZwWlZWaGtSMUZyVGt4a1ZFcFhXa2hrU0dGNlJUVldSWGhF
VmtVeFNWVnRUbHBpVjNCTVpESTVjazV0T1hOa1IxWkdZekpPUzJKSWNFSldiVlpLWVZkVk1rOUVS
bXBWYTFJMlltc3hVRk15TlVoUFZ6ZzBZVVpGTldSVk1WbFpNbEl3VjFkMGRHVnRUa2hrUjBaclZI
cEdWMUpFVGt4YVJXaFhZVVJGTWxwVWJEWk1NV2cxVG0xWmVrNVhWbEJMTUZwSVZXeHNWMXB0U2xo
U00wNDJXVzA0ZDA5WFZYcE1NVmt5VmpGa1ZHTkljRXBPTVd4eVltMXdkMVZGVVRKalZYUndUa1Zq
ZW1GV2FGbGFSRkp4VTFoUk0xcDZNRGxKYVhkcFdrZEdNRmxYZEd4bFUwazJTV3RHVWxKVlNrSlRS
type: kubernetes.io/dockerconfigjson
